import type { ObservationSet } from '@polaris/analyzer';
import { collectObservationGroupIds } from '@polaris/ai';
import type { AIProvider, AIProviderRequest, AIProviderResult, PromptDocument } from '@polaris/ai';

/**
 * The prompt embeds the real ObservationSet as
 * `<observation_set>{json}</observation_set>` (build-initial-explanation-prompt.ts)
 * — extracting it here lets the default (no explicit `groupIds`) case
 * reference a `groupId` that actually exists in whatever ObservationSet the
 * caller built the request from, rather than a hardcoded placeholder that
 * only happens to match hand-rolled fixtures.
 */
function extractDefaultGroupId(prompt: PromptDocument): string {
  const match = /<observation_set>([\s\S]*)<\/observation_set>/.exec(prompt.userPrompt);
  if (match?.[1] === undefined) {
    return 'path:0000000000000000';
  }
  const observationSet = JSON.parse(match[1]) as ObservationSet;
  const [firstGroupId] = collectObservationGroupIds(observationSet);
  return firstGroupId ?? 'path:0000000000000000';
}

/**
 * The one and only place a "Provider" is ever invoked in CI
 * (44_Development_Setup_and_Sixth_Sprint.md §99/§104/A6-24) — a real
 * `WorkerDeps.aiProvider` substitution, not a module mock
 * (46_Sprint_6_Plan_Final_Review.md F-06). By default returns a canned,
 * valid `AIExplanationModelOutput`-shaped payload with `references` filled
 * in from whatever `groupId`s the caller supplies (so Grounding Validation
 * passes against a real ObservationSet), or throws a configured error to
 * simulate a Provider failure.
 */
export class FakeAIProvider implements AIProvider {
  callCount = 0;

  constructor(
    private readonly options: {
      groupIds?: string[];
      failWith?: Error;
      findingCount?: number;
    } = {},
  ) {}

  async generateExplanation(_request: AIProviderRequest): Promise<AIProviderResult> {
    this.callCount += 1;
    if (this.options.failWith !== undefined) {
      throw this.options.failWith;
    }

    const groupId = this.options.groupIds?.[0] ?? extractDefaultGroupId(_request.prompt);
    const findingCount = this.options.findingCount ?? 1;
    const findings = Array.from({ length: findingCount }, (_, index) => ({
      title: `Fake Finding ${index + 1}`,
      observation: 'Observed via FakeAIProvider for test purposes.',
      interpretation: null,
      limitation: null,
      nextChecks: ['Check the referenced Aggregation row.'],
      references: [{ groupId }],
    }));

    return {
      provider: 'openai',
      model: 'fake-model',
      output: {
        summary: 'Fake summary generated by FakeAIProvider.',
        overallUrgency: {
          level: 'normal',
          reason: 'Fake reason for test purposes.',
          references: findingCount > 0 ? [{ groupId }] : [],
          limitations: [],
        },
        findings,
        overallNotes: [],
        dataLimitations: [],
      },
      providerResponseId: 'fake-response-id',
      usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 },
    };
  }
}
